CREATE TABLE raw.ods_raw_exam (
    raw_exam_id                         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  HE_CREATEDBY VARCHAR2(15)
, HE_CREATEDDATE TIMESTAMP
, HE_UPDATEDBY VARCHAR2(15)
, HE_UPDATEDDATE TIMESTAMP
, HE_PATIENTNO INTEGER
, HE_DOCNO INTEGER
, HE_DEPTID VARCHAR2(7)
, HE_ROOMID INTEGER
, HE_RECEPTNO INTEGER
, HE_RECEPTIDX INTEGER
, HE_EXAMTYPE VARCHAR2(13)
, HE_STATUS CHAR(1)
, HE_EXAMDATE TIMESTAMP
, HE_DOCTOR VARCHAR2(15)
, HE_MEDICAL VARCHAR2(512)
, HE_EXAMINE VARCHAR2(512)
, HE_PULSE NUMBER
, HE_TEMPERATURE NUMBER
, HE_BLOODPRESSURE INTEGER
, HE_BLOODPRESSUREX INTEGER
, HE_BREATHINTERVAL NUMBER
, HE_WEIGHT NUMBER
, HE_HEIGHT NUMBER
, HE_PREDIAGNOSTIC VARCHAR2(254)
, HE_ICD10 VARCHAR2(15)
, HE_DIAGNOSTIC VARCHAR2(1024)
, HE_TYPEID INTEGER
, HE_HASFEE CHAR(1)
, HE_PAYMENT CHAR(1)
, HE_EMERGENCY CHAR(1)
, HE_PRIORITY INTEGER
, HFE_REFROWID INTEGER
, HFE_REFSTATUS CHAR(1)
, HE_FEEIDX INTEGER
, HE_EXAMMOVE CHAR(1)
, HE_HATD CHAR(1)
, HE_ISJO CHAR(1)
, HE_ISREQ CHAR(1)
, HE_FDEPTID VARCHAR2(10)
, HE_FROOMID INTEGER
, HE_FRECEPTIDX INTEGER
, HE_REEXAM CHAR(1)
, HE_ZONE VARCHAR2(15)
, HE_CANCELBY VARCHAR2(15)
, HE_TREATTIME INTEGER
, HE_HASALLERGY CHAR(1)
, HE_IN_OUT_PKG VARCHAR2(3)
, HE_LYDOVAOVIEN VARCHAR2(128)
, HE_TOANTHAN VARCHAR2(128)
, HE_TUANHOAN VARCHAR2(128)
, HE_HOHAP VARCHAR2(128)
, HE_TIEUHOA VARCHAR2(128)
, HE_TIETNIEU VARCHAR2(128)
, HE_THANKINH VARCHAR2(128)
, HE_KHOP VARCHAR2(128)
, HE_COQUANKHAC VARCHAR2(128)
, HE_KEHOACHXN VARCHAR2(128)
, HE_KEHOACHDIEUTRI VARCHAR2(128)
, HE_TIENLUONG VARCHAR2(128)
, HE_DINHDUONG VARCHAR2(128)
, HE_PARTS CHAR(1)
, SANG_CHIEU VARCHAR2(2)
, HE_ROOMKEY INTEGER
, HE_BMI NUMBER
, HE_EXAMTYPE3 VARCHAR2(2)
, HE_DETAIL_EXAMTYPE3 VARCHAR2(2)
, HE_THOI_GIAN_DO_HUYETAP TIMESTAMP
, HE_PAIDFOR CHAR(1)
, HE_HEAD_NURSE VARCHAR2(15)
, HE_NURSE VARCHAR2(15)
, HE_PATIENT_INSTRUCTIONS VARCHAR2(128)
, HE_IS_HEALTH_EXAM CHAR(1)
,    
	batch_id                            BIGINT,

    	ingested_at                         TIMESTAMP WITHOUT TIME ZONE
                                        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_raw_exam_exam_id
        UNIQUE (HE_RECEPTIDX),

    CONSTRAINT fk_raw_exam_batch
        FOREIGN KEY (batch_id)
        REFERENCES control.batch (batch_id)
);

CREATE INDEX ix_raw_exam_patient
    ON raw.ods_raw_exam (HE_PATIENTNO);

CREATE INDEX ix_raw_exam_document
    ON raw.ods_raw_exam (HE_DOCNO);

CREATE INDEX ix_raw_exam_exam_date
    ON raw.ods_raw_exam (HE_EXAMDATE);

CREATE INDEX ix_raw_exam_updated_date
    ON raw.ods_raw_exam (HE_UPDATEDDATE);

CREATE INDEX ix_raw_exam_batch
    ON raw.ods_raw_exam (batch_id);
